### ISSUE TITLE
Метрошная вафля научилась определять приложение

### ISSUE THREAD

**Issue by Hulkmaster** [mosmetro-android/mosmetro-android#157]
```
ошибку
[+0001] ConnectionService (94056680) | Stopping by result (ERROR)
[+0001] ConnectionService (94056680) | Broadcast | ConnectionService (RUNNING = false)
[+1823] ConnectionService (113091580) | Started from DebugActivity
[+0001] ConnectionService (113091580) | Broadcast | ConnectionService (RUNNING = true)
[+0004] 7 сент. 2017 г. 10:06:36 AM
[+0000] Версия приложения: 1.7.7-61
[+0001] Подключение к сети MT_FREE
[+0000] Определение провайдера…
[+0021] Название алгоритма: MosMetroV2
[+0000] Проверка доступа в интернет
[+0012] <html>
 <head>
  <title> Web Authentication Redirect</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="-1">
  <meta http-equiv="refresh" content="1; URL=http://auth.wi-fi.ru/?segment=metro">
 </head>
 <body> 
 </body>
</html>
[+0000] http://auth.wi-fi.ru/?segment=metro
[+0000] Получение перенаправления
[+0032] CookieJar | Add: aid = 458a188fb849054cb33fc6645a7dce9797c09b7b2f259be1d64af8c95129c734
[+0000] CookieJar | Add: cookies_enabled = true
[+0004] <html>
 <head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/auth/application-22fb87162eaa2a84819ff5f3c7f73ed6b03254246cb5a3339bd53df2f97eeed1.css">
 </head>
 <body>
  <img class="data_pixels" src="http://ads.adfox.ru/220463/getDefaultImage?p1=buxxf&amp;amp;p2=v" alt="Getdefaultimage?p1=buxxf&amp;amp;p2=v">
  <img class="data_pixels" src="http://ads.adfox.ru/220463/getCode?p1=buhvd&amp;amp;p2=v&amp;amp;pe=b&amp;amp;pfc=bezbz&amp;amp;pfb=dksmt&amp;amp;pr=eslgyih" alt="Getcode?p1=buhvd&amp;amp;p2=v&amp;amp;pe=b&amp;amp;pfc=bezbz&amp;amp;pfb=dksmt&amp;amp;pr=eslgyih">
  <img class="data_pixels" src="http://top-fwz1.mail.ru/counter?id=701848;js=na" alt="Counter?id=701848;js=na">
  <img class="data_pixels" src="http://banners.adfox.ru/transparent.gif" alt="Transparent">
  <img class="data_pixels" src="http://ads.adfox.ru/220463/getCode?p1=bxvpa&amp;p2=v&amp;p3=a" alt="Getcode?p1=bxvpa&amp;p2=v&amp;p3=a">
  <div class="no-js-page" id="loader-wrapper">
   <div id="loader">
    <div class="spinner"></div>
   </div>
  </div>
  <div class="no-js-view">
   <div class="error-view" style="display: block;">
    <h1 class="message">In order to continue, enable JavaScript execution in current browser</h1>
   </div>
  </div>
 </body>
</html>
[+0000] Получение страницы авторизации
[+0036] CookieJar | Add: aid = 458a188fb849054cb33fc6645a7dce9797c09b7b2f259be1d64af8c95129c734
[+0036] CookieJar | Add: aid = 458a188fb849054cb33fc6645a7dce9797c09b7b2f259be1d64af8c95129c734
[+0006] <html>
 <head>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=no" name="viewport">
  <link rel="stylesheet" media="screen" href="/assets/pages/application-f64d871acb09f936048bd6e53d6478f6da6a76afb63b3a945b350dbe3c106351.css">
 </head>
 <body>
  <div class="main">
   <div class="content">
    <div class="message">
     <div class="info_sign"></div>
     <div class="first">
      Network access is blocked
     </div>
     <div class="second">
      Network access is blocked because your device contains software that may authorize automatically which contradicts 
      <a href="//static.wi-fi.ru/docs/offers/offer_auth.pdf">“The Terms and Conditions of Services“</a>
     </div>
     <div class="third">
      You can access the network in the normal mode in 24 hours if such program is deleted or browser configuration is changed.
     </div>
    </div>
   </div>
  </div>
  <div class="footer">
   <div class="content">
    <div class="logo-kak-doma"></div>
    <div class="text">
     You can join 
     <a href="https://pay.wi-fi.ru">“At Home”</a> service to
     <br> automatically connect and access
     <br> Internet without having to watch ads.
    </div>
   </div>
  </div>
 </body>
</html>
[+0000] Отправка формы авторизации
[+0001] java.lang.Exception: Meta tag not found
	at pw.thedrhax.mosmetro.httpclient.Client.parseMetaContent(Client.java:158)
	at pw.thedrhax.mosmetro.authenticator.providers.MosMetroV2$6.run(MosMetroV2.java:248)
	at pw.thedrhax.mosmetro.authenticator.Provider.start(Provider.java:225)
	at pw.thedrhax.mosmetro.services.ConnectionService.connect(ConnectionService.java:232)
	at pw.thedrhax.mosmetro.services.ConnectionService.main(ConnectionService.java:342)
	at pw.thedrhax.mosmetro.services.ConnectionService.onHandleIntent(ConnectionService.java:289)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

[+0000] Ошибка: сервер не ответил или вернул ошибку
[+0000] ConnectionService (113091580) | Stopping by result (ERROR)
[+0001] ConnectionService (113091580) | Broadcast | ConnectionService (RUNNING = false)
[+3615] NetworkReceiver (222233576) | Intent: android.net.wifi.STATE_CHANGE (COMPLETED)
[+0012] ConnectionService (64897190) | Started by system
[+0007] NetworkReceiver (62409447) | Wi-Fi not enabled
[+0002] ConnectionService (64897190) | Stopping by Intent
[+0011] NetworkReceiver (32798356) | Wi-Fi not enabled
[+0033] ConnectionService (64897190) | Stopping by Intent
[+0034] NetworkReceiver (196068669) | Wi-Fi not enabled
[+0005] ConnectionService (64897190) | Stopping by Intent
```

**Comment by Makc666** [comment]
повтор: https://github.com/mosmetro-android/mosmetro-android/issues/156

**Comment by TheDrHax** [comment]
То же самое почти успел написать :)

**Comment by Hulkmaster** [comment]
чуть чуть меня опередили )
