### ISSUE TITLE
Не работает "Исправление системной проверки generate_204"

### ISSUE THREAD

**Issue by Rineko** [mosmetro-android/mosmetro-android#248]
Xiaomi Mi12, MIUI 13.0.18, Android 12

Все сделано по инструкции, плюс выдано еще несколько разрешений через "Режим разработчика". При применении патча показывается ошибка:

`Exception occurred while executing 'put':
java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2266)
        at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1433)
        at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1387)
        at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:448)
        at android.content.ContentProvider.call(ContentProvider.java:2486)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
        at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:382)
        at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:278)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:50)
        at android.os.Binder.shellCommand(Binder.java:953)
        at android.os.Binder.onTransact(Binder.java:837)
        at android.os.Binder.execTransactInternal(Binder.java:1187)
        at android.os.Binder.execTransact(Binder.java:1146)`

**Comment by Suhars** [comment]
Такая же проблема на Poco X3 Pro 12 андроид. Галка Отладка по USB (настройки безопасности) не решает проблему.
